google_scraper/urls.py
from django.contrib import admin
from django.urls import path, re_path

from queries.views import QueryView, SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', QueryView.as_view(), name='find'),
    #re_path(r'^search/(?P<pk>.*)$', SearchView.as_view(), name='result'),
    path('search/<path:pk>', SearchView.as_view(), name='result'),
]

queries/models.py
from django.db import models


class Query(models.Model):
    text = models.TextField(primary_key=True)
    popular_words = models.TextField(null=False)
    num_results = models.BigIntegerField(null=False)
    client_ip = models.TextField()
    browser = models.TextField()

    def get_absolute_url(self):
        return f"/search/{self.text}"


class Link(models.Model):
    qu = models.ForeignKey(to=Query, on_delete=models.CASCADE)
    title = models.TextField()
    link = models.URLField()
    description = models.TextField()
    position = models.PositiveIntegerField()

queries/forms.py
from django import forms

from .models import Query


class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = "__all__"


class SearchForm(forms.Form):

    query = forms.CharField()
    timeout = forms.FloatField(min_value=0.0, required=False)
    browser = forms.ChoiceField(choices=(('Chrome', 'Chrome'), ('Firefox', 'Firefox')), initial='Firefox')
    proxy = forms.GenericIPAddressField(required=False)

queries/views.py
from celery.task.control import inspect
from django import views
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django_celery_results.models import TaskResult

from .forms import SearchForm
from .models import Query
from .tasks import process_data


class SearchView(views.View):

    def get(self, request, pk):
        pk = pk.lower()
        i = inspect()
        active = i.active()
        for item in active[list(active)[0]]:
            if item['args'].startswith(f"('{pk}'"):
                return render(request, 'queries/query_progress.html', {'object': item})
        try:
            item = Query.objects.get(pk=pk)
            task_result = TaskResult.objects.filter(task_args__startswith=f"('{pk}'").order_by('-date_done')[0]

            return render(request, 'queries/query_detail.html', {'object': item, 'task_result': task_result})
        except ObjectDoesNotExist:
            try:
                task_result = TaskResult.objects.filter(task_args__startswith=f"('{pk}'").order_by('-date_done')[0]
                return render(request, 'queries/query_failed.html', {'object': task_result})
            except IndexError:
                return render(request, 'queries/query_wrong.html', {'pk': pk})


class QueryView(views.View):
    form_class = SearchForm

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def get(self, request):
        form = self.form_class
        return render(request, 'queries/query_form.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        test = request.GET.get('qwert', '0')
        if form.is_valid():
            query = form.data['query'].lower()
            timeout = form.data['timeout']
            browser = form.data['browser']
            proxy = form.cleaned_data['proxy']
            try:
                timeout = float(timeout)
            except ValueError:
                timeout = 0
            client_ip = self.get_client_ip(request)
            process_data.s(query, client_ip, browser, proxy, test).apply_async(soft_time_limit=timeout)
            return redirect(f'/search/{query}')
        else:
            return render(request, 'queries/query_form.html', {'form': form})

templates/queries/query_detail.html
<h1>{{ object.text }}</h1>
<table>
    <tr>
        <th>Position</th>
        <th>Link</th>
    </tr>
    {% for item in object.link_set.all %}
    <tr>
        <td>{{ item.position }}</td>
        <td>{{ item.link }}</td>
    </tr>
    {% endfor %}
</table>


<h1>Most popular words: </h1>
<h3>{{ object.popular_words }}</h3>

<h1>Num of results: </h1>
<h3>{{ object.num_results }}</h3>

<h1>Client IP:</h1>
<h3>{{ object.client_ip }}</h3>

<h1>Browser type:</h1>
<h3>{{ object.browser }}</h3>

<h1>Last Task result:</h1>
<table>
    <tr>
        <th>task id:</th>
        <th>status:</th>
        <th>result:</th>
        <th>date of execution:</th>
        <th>traceback:</th>
        <th>task args:</th>
    </tr>
    <tr>
        <td>{{ task_result.task_id }}</td>
        <td>{{ task_result.status }}</td>
        <td>{{ task_result.result }}</td>
        <td>{{ task_result.date_done }}</td>
        <td>{{ task_result.traceback }}</td>
        <td>{{ task_result.task_args }}</td>

    </tr>


</table>

templates/queries/query_failed.html
<h1>{{ object.task_args }}</h1>

<p>{{ object.traceback }}</p>
<p>{{ object.result }}</p>
<p>{{ object.task_id }}</p>
<p>{{ object.date_done }}</p>

templates/queries/query_form.html
<html>
    <head>
        <script>
            {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
        </script>
    </head>
    <body>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    </body>
</html>

templates/queries/query_progress.html
<h1>Data for this query are prepared now...</h1>
<h2>Details about executed query:</h2>
<h1>{{ object }}</h1>

templates/queries/query_wrong.html
<h1>Query: {{ pk }} does not exists, of you want to find it go <a href="{% url 'find' %}">there</a></h1>